name: Generate Xray Credentials
description: Generate UUIDs, short IDs, and Reality key pairs using dedicated utility containers
inputs: {}
runs:
  using: composite
  steps:
    - name: Generate UUID
      id: uuid
      shell: sh
      run: |
        set -eu

        UUID=$(docker run --rm cgr.dev/chainguard/util-linux uuidgen | tr -d '\r')

        printf 'UUID=%s\n' "$UUID" >>"$GITHUB_ENV"

    - name: Generate short IDs
      id: short_ids
      shell: sh
      run: |
        set -eu

        SHORT_IDS=""
        for _ in 1 2 3; do
          ID=$(docker run --rm cgr.dev/chainguard/openssl openssl rand -hex 8 | tr -d '\r\n')
          if [ -z "$SHORT_IDS" ]; then
            SHORT_IDS="$ID"
          else
            SHORT_IDS="$SHORT_IDS $ID"
          fi
        done

        printf 'SHORT_IDS=%s\n' "$SHORT_IDS" >>"$GITHUB_ENV"

    - name: Generate Xray key pair
      id: xray_keys
      shell: sh
      run: |
        set -eu

        XRAY_KEYS=$(docker run --rm ghcr.io/xtls/xray-core:latest xray x25519)
        PRIVATE_KEY=$(printf '%s\n' "$XRAY_KEYS" | awk -F': ' '/Private key/{print $2}')
        PUBLIC_KEY=$(printf '%s\n' "$XRAY_KEYS" | awk -F': ' '/Public key/{print $2}')

        printf 'PRIVATE_KEY=%s\n' "$PRIVATE_KEY" >>"$GITHUB_ENV"
        printf 'PUBLIC_KEY=%s\n' "$PUBLIC_KEY" >>"$GITHUB_ENV"

    - name: Publish credentials
      shell: sh
      run: |
        set -eu

        OUTPUT_DIR="${RUNNER_TEMP:-/tmp}"
        mkdir -p "$OUTPUT_DIR"
        OUTPUT_FILE="$OUTPUT_DIR/xray-credentials.txt"

        set -- $SHORT_IDS
        {
          echo "XRAY_UUID: $UUID"
          echo "XRAY_SHORT_IDS:"
          for short_id in "$@"; do
            echo "  - $short_id"
          done
          echo "XRAY_PRIVATE_KEY: $PRIVATE_KEY"
          echo "XRAY_PUBLIC_KEY: $PUBLIC_KEY"
        } >"$OUTPUT_FILE"

        echo "::group::Xray Reality Credentials"
        cat "$OUTPUT_FILE"
        echo "::endgroup::"

        set -- $SHORT_IDS
        {
          echo "### Generated Xray Credentials"
          echo
          echo "- **UUID:** \`$UUID\`"
          echo "- **Short IDs:**"
          for short_id in "$@"; do
            echo "  - \`$short_id\`"
          done
          echo "- **Reality Private Key:** \`$PRIVATE_KEY\`"
          echo "- **Reality Public Key:** \`$PUBLIC_KEY\`"
          echo
          echo "> Copy the values above into your inventory or secret manager."
        } >>"$GITHUB_STEP_SUMMARY"
