name: Generate Xray Credentials

on:
  workflow_dispatch:

jobs:
  generate:
    name: Generate credentials
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/xtls/xray-core:latest
    steps:
      - name: Output Reality credentials
        shell: bash
        run: |
          set -euo pipefail

          UUID=$(xray uuid | tr -d '\r')

          mapfile -t SHORT_IDS < <(python - <<'PY'
import secrets
for _ in range(3):
    print(secrets.token_hex(4))
PY
)

          XRAY_KEYS=$(xray x25519)
          PRIVATE_KEY=$(printf '%s\n' "$XRAY_KEYS" | awk -F': ' '/Private key/{print $2}')
          PUBLIC_KEY=$(printf '%s\n' "$XRAY_KEYS" | awk -F': ' '/Public key/{print $2}')

          echo "::group::Xray Reality Credentials"
          echo "XRAY_UUID: $UUID"
          echo "XRAY_SHORT_IDS:"
          for short_id in "${SHORT_IDS[@]}"; do
            echo "  - $short_id"
          done
          echo "XRAY_PRIVATE_KEY: $PRIVATE_KEY"
          echo "XRAY_PUBLIC_KEY: $PUBLIC_KEY"
          echo "::endgroup::"

          {
            echo "### Generated Xray Credentials"
            echo
            echo "- **UUID:** \`$UUID\`"
            echo "- **Short IDs:**"
            for short_id in "${SHORT_IDS[@]}"; do
              echo "  - \`$short_id\`"
            done
            echo "- **Reality Private Key:** \`$PRIVATE_KEY\`"
            echo "- **Reality Public Key:** \`$PUBLIC_KEY\`"
            echo
            echo "> Copy the values above into your inventory or secret manager."
          } >> "$GITHUB_STEP_SUMMARY"
