name: Generate Xray Credentials

on:
  workflow_dispatch:
    inputs:
      run_label:
        description: >-
          Describe the purpose of this manual credential generation run. This
          will be shown in the job name.
        required: true
  pull_request:

jobs:
  generate:
    name: ${{ github.event_name == 'pull_request' && format('Generate credentials (PR check run #{0})', github.event.pull_request.number) || format('Generate credentials (manual run: {0})', github.event.inputs.run_label) }}
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/xtls/xray-core:latest
    steps:
      - name: Output Reality credentials
        shell: bash
        run: |
          set -euo pipefail

          UUID=$(xray uuid | tr -d '\r')

          SHORT_IDS=()
          generate_short_id() {
            if command -v od >/dev/null 2>&1; then
              od -vAn -N4 -tx1 /dev/urandom | tr -d ' \n'
            elif command -v hexdump >/dev/null 2>&1; then
              hexdump -vn4 -e '1/1 "%02x"' /dev/urandom
            else
              tr -dc 'a-f0-9' < /dev/urandom | head -c 8
            fi
          }

          for _ in 1 2 3; do
            SHORT_IDS+=("$(generate_short_id)")
          done

          XRAY_KEYS=$(xray x25519)
          PRIVATE_KEY=$(printf '%s\n' "$XRAY_KEYS" | awk -F': ' '/Private key/{print $2}')
          PUBLIC_KEY=$(printf '%s\n' "$XRAY_KEYS" | awk -F': ' '/Public key/{print $2}')

          echo "::group::Xray Reality Credentials"
          echo "XRAY_UUID: $UUID"
          echo "XRAY_SHORT_IDS:"
          for short_id in "${SHORT_IDS[@]}"; do
            echo "  - $short_id"
          done
          echo "XRAY_PRIVATE_KEY: $PRIVATE_KEY"
          echo "XRAY_PUBLIC_KEY: $PUBLIC_KEY"
          echo "::endgroup::"

          {
            echo "### Generated Xray Credentials"
            echo
            echo "- **UUID:** \`$UUID\`"
            echo "- **Short IDs:**"
            for short_id in "${SHORT_IDS[@]}"; do
              echo "  - \`$short_id\`"
            done
            echo "- **Reality Private Key:** \`$PRIVATE_KEY\`"
            echo "- **Reality Public Key:** \`$PUBLIC_KEY\`"
            echo
            echo "> Copy the values above into your inventory or secret manager."
          } >> "$GITHUB_STEP_SUMMARY"
